### ISSUE TITLE
There's a half-black screen on Lyrics Plus / Beautiful Lyrics...

### ISSUE THREAD

**Issue by SSRSMN** [spicetify/cli#3332]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.57.463.g4f748c64
Spicetify v2.39.5
```

### 📝 Description

Why is Lyrics Plus (another lyrics app) half black and only half showing?
Also, after installing a few custom apps from Spotify, it's getting super slow to start(not much of a problem)so laggy and really high input to action delay...Any fix for that?

### 📸 Screenshots

![Image](https://github.com/user-attachments/assets/9e58865c-03ba-403e-891c-00602aaae9cc)

**Comment by rxri** [comment]
I don't think you have the newest spicetify applied bc it has been already fixed

**Comment by SSRSMN** [comment]
how to apply ? isn't it spicetify update and then spicetify apply ?
also tried to update the marketplace and reinstall the app...no luck getting another issue two marketplaces are showing damn :'
![Image](https://github.com/user-attachments/assets/7332452f-26ab-46f3-9f56-1083cfa5bfb4)

**Comment by SSRSMN** [comment]
how to apply ? isn't it spicetify update and then spicetify apply ?
also tried to update the marketplace and reinstall the app...no luck getting another issue two marketplaces are showing damn :'

![Image](https://github.com/user-attachments/assets/214fab1d-8790-41f2-89a9-8d341a60146d)

**Comment by weebsplat** [comment]
I'm still encountering this issue after updating Spicetify. Might be a reoccuring issue with newer versions of Spotify as I'm running a later version than OP.

```
Spotify for Windows (64 bit)
1.2.58.498.g6afe77b7
Spicetify v2.39.5
```

![Image](https://github.com/user-attachments/assets/c5f4c896-b01b-4872-aa2c-abe2863489f8)

**Comment by rudr9090a** [comment]
same problem .. even the visualizer app is halving
any solutions uptill now?

**Comment by weebsplat** [comment]
> same problem .. even the visualizer app is halving any solutions uptill now?



> how to apply ? isn't it spicetify update and then spicetify apply ? also tried to update the marketplace and reinstall the app...no luck getting another issue two marketplaces are showing damn :'
> 
> ![Image](https://github.com/user-attachments/assets/214fab1d-8790-41f2-89a9-8d341a60146d)

I had the same issues until earlier. Turns out a theme I had installed that wasnt recently updated made the issue stick beyond the update fix, so if you have a theme installed try to delete it and reload your spotify client. That worked for me at least.

**Comment by weebsplat** [comment]
> which theme are you using?

The theme I was using when I was encountering the issue was called Throwback. Importantly it hasn't been updated in two weeks, so whatever error caused the issue in spicetify that was fixed must have remained within the code of the theme itself.

When I use no theme the issue isn't there anymore, and when I use a more recently updated theme (currently running Lucid) the issue is also not present.

**Comment by SSRSMN** [comment]
I wasn't using any themes...The stock default theme :' there are the extensions I'm using 

![Image](https://github.com/user-attachments/assets/4b03e193-618e-4abc-be21-80b3ecd8d600)

**Comment by weebsplat** [comment]
> I wasn't using any themes...The stock default theme :' there are the extensions I'm using
> 
> ![Image](https://github.com/user-attachments/assets/4b03e193-618e-4abc-be21-80b3ecd8d600)

If you're just checking beautiful lyrics, yes that still doesnt work because the extension needs to be updated.

Lyrics plus however is fully fixed to my understanding.

**Comment by SSRSMN** [comment]
Installed Spicy Lyrics, and this works fine. There are no issues whatsoever...but I liked the Beautiful Lyrics better for the mininiew :'
Now, I have three lyrics icons on Spotify😶

**btw, thanks a lot for the tips, appreciate it :)**

![Image](https://github.com/user-attachments/assets/0b777bdc-be5b-436c-8bb8-92a28641bb8e)
